name: CI/CD for Dockerized Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build and install dependencies for the Flask app
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment (optional for dependency management)
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # Build the Docker image and push it to Docker Hub
  build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code (each job is independent)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile     # Make sure the path is correct
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

      # Step 5: Log the Docker image digest
      - name: Output image digest
        run: echo "Image Digest: ${{ steps.docker_build.outputs.digest }}"
